#!/usr/bin/env python3
"""Parallax machine handoff renderer (v0.38 §5.3) — replaces the hand-written RUN-HANDOFF.md.

RUN2's continuation depended on a prose `RUN-HANDOFF.md` an operator wrote by hand: branch tips,
"both halves ready", the seam risks. This renders that artifact **deterministically** from the
machine state instead — `run-state.json` + `subagents.json` (F8) + `events.jsonl` — so a fresh
session (or `/parallax:run --adopt`) reads it and needs **no** human prose.

It is machine-RENDERED, not authored: every field comes from an artifact, and the document
contains **no free-text field an operator must fill in** (gate H1). Missing data is shown as an
explicit `(none)` / `(unknown — resolve from git)` marker, never invented.

Sections:
  * the exact resume command: `/parallax:run --adopt <slug>`;
  * integrated slices (never redone on adopt);
  * in-flight tracks — every dispatched/reported/reaped subagent with its branch, the commit
    (reported_commit, else the live branch tip resolved from git), mode, and status;
  * owed verifications — each `green-unverified` slice with its arbiter verdict + verified_diff;
  * open escalations — the count + lines from escalations.md, if any.

Deterministic: the timestamp is taken from run-state `updated_at` (override with --now), so the
same inputs render the same bytes. This is an auditability/recovery artifact, not a benchmark.

Exit: 0 rendered; 3 bad input (unreadable run-state).
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def _load(path: Path):
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _rev(repo: str, branch: str):
    if not repo or not branch:
        return None
    p = subprocess.run(["git", "-C", repo, "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"],
                       capture_output=True, text=True)
    return p.stdout.strip() if p.returncode == 0 else None


def render(a: argparse.Namespace):
    repo = a.repo
    rs_path = Path(a.run_state) if a.run_state else Path(repo) / ".parallax" / a.slug / "run-state.json"
    manifest_path = Path(a.manifest) if a.manifest else Path(repo) / ".parallax" / a.slug / "subagents.json"
    events_path = Path(a.events) if a.events else Path(repo) / ".parallax" / a.slug / "evidence" / "events.jsonl"
    esc_path = Path(a.escalations) if a.escalations else Path(repo) / ".parallax" / a.slug / "escalations.md"

    try:
        state = json.loads(rs_path.read_text(encoding="utf-8"))
    except Exception as exc:
        return 3, f"cannot read run-state {rs_path}: {exc}"
    try:
        manifest = _load(manifest_path)
    except Exception:
        manifest = None

    slug = state.get("slug", a.slug)
    when = a.now or state.get("updated_at", "(unknown)")
    lines = []
    lines.append(f"# Parallax handoff — {slug}")
    lines.append("")
    lines.append("> Machine-generated by `scripts/render-handoff.py` from run-state.json + "
                 "subagents.json + events.jsonl. Do not hand-edit; re-render instead.")
    lines.append("")
    lines.append(f"- **run_id:** `{state.get('run_id', '(unknown)')}`")
    lines.append(f"- **status at handoff:** `{state.get('status', '(unknown)')}`")
    lines.append(f"- **rendered from checkpoint at:** {when}")
    lines.append(f"- **epic base:** `{state.get('base_tip', '(unknown)')}`")
    adopted = state.get("adopted_from")
    if isinstance(adopted, dict):
        lines.append(f"- **adopted_from:** status `{adopted.get('from_status')}` "
                     f"by session `{adopted.get('by_session')}` at {adopted.get('adopted_at')}")
    lines.append("")
    lines.append("## Resume this run")
    lines.append("")
    lines.append("```")
    lines.append(f"/parallax:run --adopt {slug}")
    lines.append("```")
    lines.append("")

    slices = state.get("slices", [])
    integrated = [s.get("id") for s in slices if s.get("status") == "integrated"] or \
                 list(state.get("integrated", []))
    lines.append("## Integrated slices (never redone on adopt)")
    lines.append("")
    lines.append(("- " + ", ".join(f"`{sid}`" for sid in integrated)) if integrated else "- (none)")
    lines.append("")

    lines.append("## In-flight tracks (dispatched subagents)")
    lines.append("")
    inflight_rows = []
    if isinstance(manifest, dict):
        for e in manifest.get("entries", []):
            if e.get("status") == "stale":
                commit = "(branch gone — STALE, resolve from git)"
            else:
                commit = e.get("reported_commit") or _rev(repo, e.get("branch")) or "(unknown — resolve from git)"
            inflight_rows.append((e.get("slice"), e.get("role"), e.get("branch"),
                                  e.get("mode"), e.get("status"), commit))
    if inflight_rows:
        lines.append("| slice | role | branch | mode | status | commit |")
        lines.append("|---|---|---|---|---|---|")
        for slice_id, role, branch, mode, status, commit in inflight_rows:
            lines.append(f"| `{slice_id}` | {role} | `{branch}` | {mode} | {status} | `{commit}` |")
    else:
        lines.append("- (none recorded — no subagents.json, or no tracks dispatched)")
    lines.append("")

    owed = [s for s in slices if s.get("status") == "green-unverified"]
    lines.append("## Owed verifications (green-unverified — arbiter passed, cross-model verify still owed)")
    lines.append("")
    if owed:
        lines.append("| slice | arbiter_verdict | verified_diff |")
        lines.append("|---|---|---|")
        for s in owed:
            lines.append(f"| `{s.get('id')}` | {s.get('arbiter_verdict', '(none)')} | "
                         f"`{s.get('verified_diff', '(none)')}` |")
    else:
        lines.append("- (none)")
    lines.append("")

    lines.append("## Open escalations")
    lines.append("")
    esc_text = None
    try:
        if esc_path.exists():
            esc_text = esc_path.read_text(encoding="utf-8").strip()
    except Exception:
        esc_text = None
    if esc_text:
        lines.append(f"See `{esc_path.name}`:")
        lines.append("")
        for ln in esc_text.splitlines():
            lines.append(f"> {ln}")
    else:
        lines.append("- (none)")
    lines.append("")

    out = "\n".join(lines) + "\n"
    out_path = Path(a.out) if a.out else Path(repo) / ".parallax" / slug / "handoff.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="utf-8")
    return 0, str(out_path)


def main(argv) -> int:
    ap = argparse.ArgumentParser(description="Parallax v0.38 machine handoff renderer (deterministic).")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--slug", required=True)
    ap.add_argument("--prefix", default="feature/")
    ap.add_argument("--run-state", default=None)
    ap.add_argument("--manifest", default=None)
    ap.add_argument("--events", default=None)
    ap.add_argument("--escalations", default=None)
    ap.add_argument("--out", default=None, help="default: <repo>/.parallax/<slug>/handoff.md")
    ap.add_argument("--now", default=None, help="timestamp override (default: run-state updated_at)")
    a = ap.parse_args(argv)
    code, detail = render(a)
    if code != 0:
        print(json.dumps({"error": detail}))
    else:
        print(json.dumps({"rendered": detail}))
    return code


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
